/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canvas_formatter;

/**
 *
 * @author devinmuzzy
 */
import java.awt.MouseInfo;

public class ErrorFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form ErrorFrame
	 */
	public ErrorFrame(String message) {
		initComponents();
		errorOptionPane.setVisible(true);
		System.out.println("FRAME CREATED WITH MESSAGE");
		// errorPane.setText(message);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		errorOptionPane = new javax.swing.JOptionPane();
		errorDialog = new javax.swing.JDialog();
		jLabel16 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jScrollPane7 = new javax.swing.JScrollPane();
		errorPane = new javax.swing.JTextPane();

		errorOptionPane.setMessage("Error Reached");
		errorOptionPane.setMessageType(0);
		errorOptionPane.setToolTipText("");
		errorOptionPane.setName("Error"); // NOI18N

		errorDialog.setTitle("Error");
		errorDialog.setAlwaysOnTop(true);
		errorDialog.setLocation(MouseInfo.getPointerInfo().getLocation());
		errorDialog.setSize(new java.awt.Dimension(228, 237));

		jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
		jLabel16.setForeground(new java.awt.Color(255, 0, 51));
		jLabel16.setText("ERROR");

		jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
		jLabel17.setText("Please check your authentication token and ");

		jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
		jLabel18.setText("institution to resolve the error.");

		jScrollPane7.setViewportView(errorPane);

		javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
		errorDialog.getContentPane().setLayout(errorDialogLayout);
		errorDialogLayout.setHorizontalGroup(errorDialogLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(errorDialogLayout.createSequentialGroup().addContainerGap()
						.addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jSeparator1)
								.addGroup(errorDialogLayout.createSequentialGroup()
										.addGroup(errorDialogLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(errorDialogLayout.createSequentialGroup().addGap(6, 6, 6)
														.addComponent(jLabel18))
												.addComponent(jScrollPane7))
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap())
				.addGroup(errorDialogLayout.createSequentialGroup().addGap(26, 26, 26).addComponent(jLabel16)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		errorDialogLayout.setVerticalGroup(errorDialogLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(errorDialogLayout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel17)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel18)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
						.addContainerGap()));

		errorDialog.getAccessibleContext().setAccessibleDescription("");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JDialog errorDialog;
	private javax.swing.JOptionPane errorOptionPane;
	private javax.swing.JTextPane errorPane;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JSeparator jSeparator1;
	// End of variables declaration
}
